Implement bitwise operations for negative numbers
nim-lang/bigints pull request #111
Opened 2022-07-28 13:55 UTC by konsumlamm

Fixes #51.

2022-08-01 09:53 UTC, dlesnoff requested changes
The test outputs look consistent with my tests in python3.
I would simply consider moving the implementation's choice to the README.md and remove some function calls.
Even though the algorithm is more explicit with these calls, it may add unuseful copies.

2022-08-01 09:53 UTC, dlesnoff commented on src/bigints.nim
> +## The bitwise operations behave as if negative numbers were represented in 2's complement.
I wonder whether the choices we make in the library's implementation should not rather be added to Readme.
They are redundant information with the source code (though easier to read), and are interesting to the end-user, which will not look at source code.

2022-08-01 09:53 UTC, dlesnoff commented on src/bigints.nim
> +      let b = invertIn(b)
a and b are negative. So we are not changing the isNegative field and we are only decrementing them.
We can avoid these calls to invertIn, and simply decrementing them.
It avoids one function call, one copy into result and one affectation

2022-08-01 09:53 UTC, dlesnoff commented on tests/tbigints.nim
> +
Probably a whitespace on a blank line I added in a previous commit :'(. Sorry for this.

2022-08-01 09:53 UTC, dlesnoff commented on src/bigints.nim
> +        result.limbs[i] = (not a.limbs[i]) and b.limbs[i]
Same as above.

2022-08-01 11:08 UTC, konsumlamm commented on src/bigints.nim
> +## The bitwise operations behave as if negative numbers were represented in 2's complement.
This is a doc comment, it will appear in the [generated documentation of this library](https://nimdocs.com/nim-lang/bigints/bigints.html), which I'd expect users to read. Imo the readme is more about general information on the library and it already mentions the bitwise operators, now without the note that they don't work for negative numbers.

2022-08-01 11:09 UTC, konsumlamm commented on tests/tbigints.nim
> +
A tip: You can configure your editor to remove trailing whitespace automatically when saving.

2022-08-01 11:28 UTC, konsumlamm commented on src/bigints.nim
> +      let b = invertIn(b)
Wdym? The `isNegative` fields are changed from `true` to `false`, so that the decrementing is correct (we need the absolute value minus one). I think however that we can instead increment the number (and ignore the `isNegative` field). I highly doubt that `invertIn`/`invertOut` aren't already inlined (avoiding the function call and potential copy), but I should probably check that.

2022-08-01 12:36 UTC, dlesnoff commented on src/bigints.nim
> +      let b = invertIn(b)
I made a confusion between isNegative and isPositive.
Yes, that is exactly what I propose. We have already test their sign, so let's just decrement them. If we can even avoid the creation of the two temporaries (by integrating the +1 directly in the operations) it would be much better.
For 1024 limbs BigInts a and b, we copy 2048 limbs for temporaries in addition to the 1024 allocated for the result, just to do one `a and b`.

2022-08-01 13:22 UTC, konsumlamm commented on src/bigints.nim
> +      let b = invertIn(b)
They're inlined when adding an `{.inline.}` pragma, so I did that.

2022-11-02 17:48 UTC, konsumlamm commented
@narimiran I think this is ready to be merged now.

2022-11-03 08:48 UTC, merged