Fix `shl` and `shr`
nim-lang/bigints pull request #134
Opened 2023-07-23 12:33 UTC by konsumlamm

`shl` could create invalid zero values, by shifting 0.

`shr` could raise an exception when the shift is too big.

2023-07-24 19:27 UTC, dlesnoff requested changes
This is nicer, but I would avoid a few computations in this edge case.

2023-07-24 19:27 UTC, dlesnoff commented on src/bigints.nim
> +    return zero
I would put that before computation of b and mask.

2023-07-24 19:36 UTC, konsumlamm commented on src/bigints.nim
> +    return zero
I would expect the (C) compiler to automatically reorder that, but sure, I can do that.

2023-07-28 18:51 UTC, konsumlamm commented
@narimiran can this be merged?

2023-07-28 19:09 UTC, merged